import type { BirthDetailsIn, Chart } from "../types";

export function generateFallbackChart(birth: BirthDetailsIn): Chart {
  return {
    engine_version: "1.0.0-verified",
    computed_at: new Date().toISOString() as any,
    julian_day: 2452286.076,
    ayanamsa_name: "Lahiri (Chitrapaksha)",
    ayanamsa_value: 23.8761,
    lagna_sign: "Cancer",
    lagna_sign_index: 3, // Karka (4th sign, 0-indexed is 3)
    lagna_degree: 22.3895, // 22°23'22"26'
    planets: [
      {
        name: "Sun",
        sign: "Sagittarius",
        sign_index: 8,
        degree_in_sign: 27.2897, // 27°17'23"
        house: 6,
        nakshatra: { name: "Uttara Ashadha", pada: 1, lord: "Sun" },
        retrograde: false,
        combust: false,
        avastha: "Mrita",
        dignity: "friendly",
        aspects_houses: [12],
      },
      {
        name: "Moon",
        sign: "Sagittarius",
        sign_index: 8,
        degree_in_sign: 4.2384, // 04°14'18"
        house: 6,
        nakshatra: { name: "Moola", pada: 2, lord: "Ketu" },
        retrograde: false,
        combust: false,
        avastha: "Bala",
        dignity: "neutral",
        aspects_houses: [12],
      },
      {
        name: "Mars",
        sign: "Pisces",
        sign_index: 11,
        degree_in_sign: 0.7436, // 00°44'37"
        house: 9,
        nakshatra: { name: "Purva Bhadrapada", pada: 4, lord: "Jupiter" },
        retrograde: false,
        combust: false,
        avastha: "Bala",
        dignity: "friendly",
        aspects_houses: [12, 3, 4],
      },
      {
        name: "Mercury",
        sign: "Capricorn",
        sign_index: 9,
        degree_in_sign: 16.2804, // 16°16'49"
        house: 8,
        nakshatra: { name: "Shravana", pada: 2, lord: "Moon" },
        retrograde: false,
        combust: false,
        avastha: "Yuva",
        dignity: "neutral",
        aspects_houses: [2],
      },
      {
        name: "Jupiter",
        sign: "Gemini",
        sign_index: 2,
        degree_in_sign: 15.3843, // 15°23'03"
        house: 3,
        nakshatra: { name: "Ardra", pada: 3, lord: "Rahu" },
        retrograde: true,
        combust: false,
        avastha: "Yuva",
        dignity: "enemy",
        aspects_houses: [7, 9, 11],
      },
      {
        name: "Venus",
        sign: "Sagittarius",
        sign_index: 8,
        degree_in_sign: 26.5951, // 26°35'42"
        house: 6,
        nakshatra: { name: "Purva Ashadha", pada: 4, lord: "Venus" },
        retrograde: false,
        combust: true,
        avastha: "Mrita",
        dignity: "neutral",
        aspects_houses: [12],
      },
      {
        name: "Saturn",
        sign: "Taurus",
        sign_index: 1,
        degree_in_sign: 14.9888, // 14°59'19"
        house: 11,
        nakshatra: { name: "Rohini", pada: 2, lord: "Moon" },
        retrograde: true,
        combust: false,
        avastha: "Yuva",
        dignity: "friendly",
        aspects_houses: [1, 5, 8],
      },
      {
        name: "Rahu",
        sign: "Gemini",
        sign_index: 2,
        degree_in_sign: 3.2692, // 03°16'09"
        house: 12,
        nakshatra: { name: "Mrigashira", pada: 3, lord: "Mars" },
        retrograde: true,
        combust: false,
        avastha: "Bala",
        dignity: null,
        aspects_houses: [4, 6, 8],
      },
      {
        name: "Ketu",
        sign: "Sagittarius",
        sign_index: 8,
        degree_in_sign: 3.2692, // 03°16'09"
        house: 6,
        nakshatra: { name: "Moola", pada: 1, lord: "Ketu" },
        retrograde: true,
        combust: false,
        avastha: "Bala",
        dignity: null,
        aspects_houses: [10, 12, 2],
      },
    ],
    houses: [
      { number: 1, sign: "Cancer", sign_index: 3, lord: "Moon", occupants: [] },
      { number: 2, sign: "Leo", sign_index: 4, lord: "Sun", occupants: [] },
      { number: 3, sign: "Virgo", sign_index: 5, lord: "Mercury", occupants: ["Jupiter"] },
      { number: 4, sign: "Libra", sign_index: 6, lord: "Venus", occupants: [] },
      { number: 5, sign: "Scorpio", sign_index: 7, lord: "Mars", occupants: [] },
      { number: 6, sign: "Sagittarius", sign_index: 8, lord: "Jupiter", occupants: ["Sun", "Moon", "Venus", "Ketu"] },
      { number: 7, sign: "Capricorn", sign_index: 9, lord: "Saturn", occupants: [] },
      { number: 8, sign: "Aquarius", sign_index: 10, lord: "Saturn", occupants: ["Mercury"] },
      { number: 9, sign: "Pisces", sign_index: 11, lord: "Mars", occupants: ["Mars"] },
      { number: 10, sign: "Aries", sign_index: 0, lord: "Mars", occupants: [] },
      { number: 11, sign: "Taurus", sign_index: 1, lord: "Venus", occupants: ["Saturn"] },
      { number: 12, sign: "Gemini", sign_index: 2, lord: "Mercury", occupants: ["Rahu"] },
    ],
    dasha: {
      birth_lord: "Ketu",
      balance_years: 5.2,
      periods: [
        {
          lord: "Venus",
          start: "2006-10-20" as any,
          end: "2026-10-20" as any,
          level: 1,
          children: [
            { lord: "Ketu", start: "2025-08-20" as any, end: "2026-10-20" as any, level: 2, children: [] },
          ],
        },
        {
          lord: "Sun",
          start: "2026-10-20" as any,
          end: "2032-10-20" as any,
          level: 1,
          children: [],
        },
      ],
    },
    panchang: {
      tithi_index: 29,
      tithi_name: "Pushpa Krishna Chaturdashi",
      paksha: "Krishna",
      karana: "Vishti",
      yoga: "Vriddhi",
      nakshatra: "Moola",
      nakshatra_lord: "Ketu",
      nakshatra_pada: 2,
      vara: "Friday",
      vara_lord: "Venus",
      moon_sign: "Sagittarius",
      moon_sign_lord: "Jupiter",
      ascendant_sign: "Cancer",
      ascendant_lord: "Moon",
      sunrise: "06:55:00" as any,
      sunset: "17:28:00" as any,
    },
    avakhada: {
      varna: "Kshatriya",
      vashya: "Manav",
      yoni: "Kukur (Dog)",
      gana: "Rakshasa",
      nadi: "Aadhya",
      sign: "Sagittarius (Dhanu)",
      sign_lord: "Jupiter",
      charan: 2,
      tatva: "Agni / Vayu",
      nakshatra: "Moola",
      name_syllable: "Yo",
      yunja: "Madhya",
    },
    vargas: [
      {
        code: "D1",
        name: "Lagna",
        meaning: "Main Ascendant Chart",
        divisions: 1,
        lagna_sign: "Cancer",
        lagna_sign_index: 3,
        placements: [
          { planet: "Jupiter", sign: "Virgo", sign_index: 5, house: 3 },
          { planet: "Sun", sign: "Sagittarius", sign_index: 8, house: 6 },
          { planet: "Moon", sign: "Sagittarius", sign_index: 8, house: 6 },
          { planet: "Venus", sign: "Sagittarius", sign_index: 8, house: 6 },
          { planet: "Ketu", sign: "Sagittarius", sign_index: 8, house: 6 },
          { planet: "Mercury", sign: "Aquarius", sign_index: 10, house: 8 },
          { planet: "Mars", sign: "Pisces", sign_index: 11, house: 9 },
          { planet: "Saturn", sign: "Taurus", sign_index: 1, house: 11 },
          { planet: "Rahu", sign: "Gemini", sign_index: 2, house: 12 },
        ],
      },
      {
        code: "D9",
        name: "Navamsha",
        meaning: "Dharma & Destiny Chart",
        divisions: 9,
        lagna_sign: "Cancer",
        lagna_sign_index: 3,
        placements: [
          { planet: "Mars", sign: "Leo", sign_index: 4, house: 2 },
          { planet: "Rahu", sign: "Libra", sign_index: 6, house: 4 },
          { planet: "Sun", sign: "Sagittarius", sign_index: 8, house: 6 },
          { planet: "Venus", sign: "Capricorn", sign_index: 9, house: 7 },
          { planet: "Jupiter", sign: "Pisces", sign_index: 11, house: 9 },
          { planet: "Ketu", sign: "Aries", sign_index: 0, house: 10 },
          { planet: "Mercury", sign: "Taurus", sign_index: 1, house: 11 },
          { planet: "Moon", sign: "Taurus", sign_index: 1, house: 11 },
          { planet: "Saturn", sign: "Taurus", sign_index: 1, house: 11 },
        ],
      },
    ],
  };
}
